Move LowPriorityImplicits to a com.softwaremill.quicklens to avoid conflicts with other softwaremill libraries
softwaremill/quicklens pull request #238
Opened 2024-08-12 16:16 UTC by KacperFKorban

closes #237

2024-08-12 18:41 UTC, slandelle requested changes
One small nit.
Thanks!

2024-08-12 18:41 UTC, slandelle commented on quicklens/src/main/scala-2.13+/com.softwaremill.quicklens/LowPriorityImplicits.scala
> +}
Missing EOL

2024-08-13 08:20 UTC, slandelle requested changes
LGTM

It might be cleaner fix the `com.softwaremill.quicklens` folder into a proper `com/softwaremill/quicklens` hierarchy.

2024-08-13 08:20 UTC, slandelle approved these changes

2024-09-02 09:53 UTC, merged

2024-09-02 09:53 UTC, adamw commented
Thanks!